"""`dnfw symbols` -- list the C++ names in a section, or seed them into Ghidra."""

import pathlib

from ..firmware.load import load
from ..image import symbols as finder
from ..image.coldfire import LoadedImage
from .files import read_image

NAME = "symbols"
HELP = "list the RTTI type names and mangled symbols GCC left in a section"

MAIN_OS = 3


def configure(parser) -> None:
    parser.add_argument("image", type=pathlib.Path, help=".syx file, or a .zip containing one")
    parser.add_argument(
        "--section", type=int, default=MAIN_OS, help="section id (default: 3, MAIN OS)"
    )
    parser.add_argument("--kind", choices=("type", "mangled"), help="show only one kind")
    parser.add_argument("--grep", help="show only names containing this substring")
    parser.add_argument(
        "--ghidra",
        type=pathlib.Path,
        metavar="FILE",
        help="write a Ghidra script that labels each address instead of listing",
    )


def run(args) -> int:
    firmware = load(read_image(args.image))
    section = firmware.container.find(args.section)
    if section is None:
        raise ValueError(f"image has no section id={args.section}")
    content = section.unpack()
    if content is None:
        raise ValueError(f"section id={args.section} is stored raw, not code")

    found = finder.find(LoadedImage(dest=section.dest, content=content))
    if args.kind:
        found = [s for s in found if s.kind == args.kind]
    if args.grep:
        found = [s for s in found if args.grep in s.text]

    if args.ghidra:
        args.ghidra.write_text(_ghidra_script(found), encoding="utf-8")
        print(f"  wrote {args.ghidra}  ({len(found):,} labels)")
        return 0

    for symbol in found:
        print(f"0x{symbol.address:08x}  {symbol.kind:<7}  {symbol.text}")
    print(f"  {len(found):,} names")
    return 0


def _ghidra_script(found) -> str:
    """A Ghidra Python script that puts a label on each name's address.

    Labels, not symbols on functions: these addresses are where the *string*
    lives, which is what lets a reader find the vtable and the type that refer
    to it. Turning those into function names is a later, and manual, step.
    """
    lines = [
        "# Generated by `dnfw symbols --ghidra`. Run in Ghidra's Script Manager",
        "# against the depacked section, imported at its load address.",
        "from ghidra.program.model.symbol import SourceType",
        "",
        "NAMES = [",
    ]
    lines += [f"    (0x{s.address:08x}, {s.text!r})," for s in found]
    lines += [
        "]",
        "",
        "space = currentProgram.getAddressFactory().getDefaultAddressSpace()",
        "for address, text in NAMES:",
        "    createLabel(space.getAddress(address), 'rtti_' + text, True, SourceType.ANALYSIS)",
        f"print('labelled %d names' % len(NAMES))",
        "",
    ]
    return "\n".join(lines)
