"""The platform: one start-up loader and one appended area, shared by every mod.

A mod that needs more room than a cave appends a **chunk**, not an image tail.
The platform owns the three things those mods used to claim each for itself:

- the start-up calls at `0x4000053e`, `jsr data_init ; jsr bss_clear`, replaced
  by one call to the loader;
- the loader, `csrc/runtime/loader.S`, in the clean 138-byte cave at `0x4028da6e`;
- the appended `DNFW` area past the end of MAIN OS (`dnfw.patch.area`).

The loader copies the area's header and its data chunks to `RUNTIME_VA` plus
their offset, and each `CODE` chunk to its own load address, before the BSS
clear. So a second mod does not undo the first: it **adds** its chunks to the
area that is already there (`join`). That is octabam's platform loader and
elekloader's core, reduced to what this firmware needs (`docs/references.md`).

## Order

`join` places data chunks before `CODE` chunks, so the data window stays small
(it must end below `DATA_LIMIT`). A data chunk is found by its id at run time
(the boot screen's stamp walks the directory), never by a fixed address, so
its offset may change from one combination to the next. A `CODE` chunk runs
at its own load address, which does not move.

## RAM

Every run-time range is checked before the area is written: the header and
the data chunks inside the data window, and each `CODE` chunk's image and BSS
against the window and against every other chunk. RAM a mod uses without a
chunk (lfowaves' NOIS state, arpplocks' shadow sounds) is declared by that mod
(`ram()`) and checked pairwise with its extents, like any byte range.

## Displaced instructions

A hook overwrites stock instructions with a jump and replays them in its own
code. If a second mod edits those instructions (lfo4 widens the parameter
table's bound, and lfowaves' `getShortName` hook displaced the compare that
holds it), the edit must land on the **replayed copy**, or it finds no stock
bytes and refuses. So a hook records what it moved in a `DISP` chunk: the
site, its length, and where the copy runs. `write` redirects an edit inside a
displaced site to the copy, after checking the copy still holds the stock
bytes. The copy must be the displaced bytes unchanged, which is only true of
position-independent instructions; a hook that re-encodes them may not record
them. A `DISP` chunk is 12 bytes per site and is copied up with the data like
any other; nothing reads it at run time.

One subject: installing that loader and assembling that area. The bytes are
generated by `scripts/gen_platform_code.py` into `platform_code.json`, so the
browser applies exactly what the CLI does.
"""

from __future__ import annotations

import json
import pathlib
import struct

from . import RAM, Extent, ModError
from ..patch import area

ID = "platform"
SECTION = 3                        # MAIN OS
BASE = 0x40000400
SPEC = json.loads((pathlib.Path(__file__).with_name("platform_code.json")).read_text())

STOCK_LENGTH = SPEC["stock_length"]
RUNTIME_VA = area.RUNTIME_VA       # the data window: the header, then the data chunks
DATA_LIMIT = SPEC["data_limit"]    # the window ends below lfowaves' NOIS state


def extents(area_length: int = 0) -> list[Extent]:
    """What the platform writes. A mod on it declares these too (they are
    owned by the platform, so two mods declaring them do not conflict)."""
    out = [Extent(SECTION, SPEC["calls_va"] - BASE, len(SPEC["calls_stock"]) // 2,
                  "start-up calls -> the platform loader", ID),
           Extent(SECTION, SPEC["cave_va"] - BASE, SPEC["cave_cap"], "the platform loader's cave", ID)]
    if area_length:
        out.append(Extent(SECTION, STOCK_LENGTH, area_length, "the appended DNFW area", ID))
    return out


def ram() -> list[Extent]:
    return [Extent(RAM, RUNTIME_VA, DATA_LIMIT - RUNTIME_VA,
                   "the data window: the area header and its data chunks", ID)]


def split(content: bytes) -> tuple[bytes, list[tuple[bytes, bytes]]]:
    """MAIN OS -> (MAIN OS without the area, the chunks already in it).

    Stock length: nothing appended. Longer: the tail must be a DNFW area and
    the loader must be installed, or another tool appended something this
    platform does not know, and it is refused rather than overwritten.
    """
    if len(content) < STOCK_LENGTH:
        raise ModError(f"MAIN OS is {len(content):,} B, shorter than {STOCK_LENGTH:,}: "
                       "not Digitone II 1.11")
    if len(content) == STOCK_LENGTH:
        return bytes(content), []
    if not installed(content):
        raise ModError("MAIN OS carries appended data but not the platform loader: "
                       "it was built by something else; start from stock 1.11")
    try:
        chunks = area.parse(bytes(content[STOCK_LENGTH:]))
    except area.AreaError as exc:
        raise ModError(f"the appended area: {exc}") from None
    return bytes(content[:STOCK_LENGTH]), chunks


def installed(content: bytes) -> bool:
    at = SPEC["calls_va"] - BASE
    return bytes(content[at:at + len(SPEC["hook"]) // 2]).hex() == SPEC["hook"]


def join(base: bytes, chunks: list[tuple[bytes, bytes]]) -> bytes:
    """MAIN OS without an area + chunks -> MAIN OS with the loader and the area."""
    if len(base) != STOCK_LENGTH:
        raise ModError(f"MAIN OS is {len(base):,} B, not {STOCK_LENGTH:,}")
    content = bytearray(base)
    calls = SPEC["calls_va"] - BASE
    cave = SPEC["cave_va"] - BASE
    loader = bytes.fromhex(SPEC["loader"])
    link = SPEC["link_va"] - BASE
    if not installed(content):
        if content[calls:calls + len(SPEC["calls_stock"]) // 2].hex() != SPEC["calls_stock"]:
            raise ModError(f"0x{SPEC['calls_va']:08x} holds neither the stock start-up calls "
                           "nor the platform loader's call: another mod has changed it")
        if any(content[cave:cave + SPEC["cave_cap"]]):
            raise ModError(f"the platform loader's cave at 0x{SPEC['cave_va']:08x} is in use")
        content[link:link + len(loader)] = loader
        hook = bytes.fromhex(SPEC["hook"])
        content[calls:calls + len(hook)] = hook
    elif bytes(content[link:link + len(loader)]) != loader:
        raise ModError("the start-up call reaches a loader that is not this platform's")

    ordered = sorted(chunks, key=lambda c: c[0] == area.CODE)     # data first; stable
    blob = area.build(ordered)
    check_runtime(blob)
    return bytes(content + blob + bytes(-len(blob) % 4))


def check_runtime(blob: bytes) -> None:
    """Refuse an area whose run-time ranges overlap or leave the data window."""
    count = struct.unpack_from(">I", blob, 8)[0]
    head = 12 + 12 * count
    window_end = RUNTIME_VA + head
    ranges = []
    for cid, data in area.parse(blob):
        if cid == area.CODE:
            code = area.CodeChunk.unpack(data)
            ranges.append((code.load, code.load + len(code.image) + code.bss,
                           f"CODE at 0x{code.load:08x}"))
        else:
            window_end = max(window_end, area.runtime_address(blob, cid) + len(data))
    if window_end > DATA_LIMIT:
        raise ModError(f"the data chunks run to 0x{window_end:08x}, past the data window's "
                       f"end 0x{DATA_LIMIT:08x}")
    ranges.append((RUNTIME_VA, DATA_LIMIT, "the data window"))
    ranges.sort()
    for (a_lo, a_hi, a), (b_lo, b_hi, b) in zip(ranges, ranges[1:]):
        if b_lo < a_hi:
            raise ModError(f"{a} and {b} overlap at run time (0x{b_lo:08x}..0x{min(a_hi, b_hi):08x})")


def runtime(content: bytes) -> list[tuple[int, bytes]]:
    """What the loader leaves in RAM for MAIN OS CONTENT: [(address, bytes)].

    The area's header and each data chunk at `RUNTIME_VA` + its offset, each
    `CODE` chunk's image at its load address followed by its zeroed BSS. For a
    harness that starts past boot and must install the area by hand.
    """
    _, chunks = split(content)
    if not chunks:
        return []
    blob = bytes(content[STOCK_LENGTH:])
    head = 12 + 12 * struct.unpack_from(">I", blob, 8)[0]
    out = [(RUNTIME_VA, blob[:head])]
    for cid, data in area.parse(blob):
        if cid == area.CODE:
            code = area.CodeChunk.unpack(data)
            out.append((code.load, code.image + bytes(code.bss)))
        else:
            out.append((area.runtime_address(blob, cid), data))
    return out


DISP = b"DISP"


def displace(site_va: int, length: int, copy_va: int) -> tuple[bytes, bytes]:
    """The chunk recording that LENGTH stock bytes at SITE_VA now run at COPY_VA."""
    return DISP, struct.pack(">III", site_va, length, copy_va)


def displaced(chunks) -> list[tuple[int, int, int]]:
    out = []
    for cid, data in chunks:
        if cid == DISP:
            out += [struct.unpack_from(">III", data, at) for at in range(0, len(data), 12)]
    return out


def write(content: bytearray, chunks: list, va: int, stock: bytes, new: bytes, what: str = "") -> None:
    """Write NEW over STOCK at VA, in CONTENT or, if another mod's hook displaced
    those bytes, in the copy its CODE chunk replays (CHUNKS is updated in place)."""
    label = f"0x{va:08x}{' (' + what + ')' if what else ''}"
    for site, length, copy in displaced(chunks):
        if va + len(stock) <= site or site + length <= va:
            continue
        if not (site <= va and va + len(stock) <= site + length):
            raise ModError(f"{label} straddles a site another mod's hook displaced "
                           f"(0x{site:08x}, {length} B)")
        target = copy + (va - site)
        for i, (cid, data) in enumerate(chunks):
            if cid != area.CODE:
                continue
            code = area.CodeChunk.unpack(data)
            if not code.load <= target < code.load + len(code.image):
                continue
            image = bytearray(code.image)
            at = target - code.load
            if bytes(image[at:at + len(stock)]) != stock:
                raise ModError(f"{label} is not stock in the copy at 0x{target:08x}; "
                               "another mod has changed it")
            image[at:at + len(new)] = new
            chunks[i] = (cid, area.CodeChunk(code.load, bytes(image), code.bss, code.init).pack())
            return
        raise ModError(f"{label}: the displaced copy at 0x{target:08x} is in no CODE chunk")
    at = va - BASE
    if bytes(content[at:at + len(stock)]) != stock:
        raise ModError(f"{label} is not stock ({bytes(content[at:at + 12]).hex()}...); another "
                       "mod has changed it, or this is not Digitone II 1.11")
    content[at:at + len(new)] = new


def add(content: bytes, chunks: list[tuple[bytes, bytes]]) -> bytes:
    """Add CHUNKS to MAIN OS CONTENT, whatever it already carries."""
    base, have = split(content)
    return join(base, have + list(chunks))
