/* The noise and sub strip (noise_strip.h).
 *
 * DEC is the outline: column k is k / NOISE_ENV_WIDTH s after the note (noise_env.h,
 * generated by scripts/gen_noise_env.py). OCT is cycles across the strip: -1 oct four,
 * -2 two, -3 one, so every shape shows whole at every octave. */
#include "noise_strip.h"
#include "canvas.h"
#include "noise_env.h"
#include "../synth/fixq16.h"
#include "../synth/noise_q16.h"
#include "../synth/sub_q16.h"

#define STRIP_SEED   0x9E3779B9u
#define STRIP_WARMUP 256                /* samples before the first column: the filters settle */

static int to_row(int y, int unit, int half)
{
    int r = (y * unit + 0x8000) >> 16;
    return r > half ? half : r < -half ? -half : r;
}

void noise_strip_draw(void *c, const struct noise_strip_values *v,
                      const struct strip_box *b, int glyph)
{
    int type = v->type < NOISE_TYPES ? v->type : NOISE_DIG;
    int shape = v->shape < SUB_SHAPES ? v->shape : SUB_PLS;
    int octave = v->octave < 2 ? v->octave : 2;
    int cy = (b->y0 + b->y1) >> 1, half = (b->y1 - b->y0) >> 1;
    int w = b->x1 - b->x0 + 1;
    unsigned sub_step = ((0xFFFFFFFFu / (unsigned)w) * 4u) >> octave, sub_phase = 0;
    struct noise_q16 n;
    noise_q16_init(&n, STRIP_SEED);
    for (int i = 0; i < STRIP_WARMUP; i++)
        noise_q16_next(&n, type, v->colr);
    int last = 0, sub_last = 0;
    for (int k = 0; k < w; k++) {
        int y = q16_level(noise_q16_next(&n, type, v->colr), v->nois);
        if (v->dec < 127)
            y = noise_q16_decay(&n, y, noise_env[v->dec]);
        int sy = q16_level(sub_q16(sub_phase, shape), v->sub);
        sub_phase += sub_step;
        int col = b->x0 + k;
        if (glyph == STRIP_SUM) {
            int r = to_row(y + sy, b->unit, half);
            canvas_column(c, col, cy + (k ? last : r), cy + r);
            last = r;
            continue;
        }
        int r = to_row(y, b->unit, half);
        if (!v->sub || !(k & 1))                    /* under a sub, the noise dotted */
            canvas_column(c, col, cy + (k ? last : r), cy + r);
        last = r;
        if (v->sub) {
            int q = to_row(sy, b->unit, half);
            canvas_column(c, col, cy + (k ? sub_last : q), cy + q);
            sub_last = q;
        }
    }
}
