"""Does the DSP act on mirror block 16? One cave, one store, one question.

    python scripts/build_fxblock16.py

`docs/fx-master-modulation.md` §6 names this as the cheapest experiment the
whole FX-modulation question turns on. That document reads, from ColdFire code
alone, that the per-track parameter mirror is **seventeen** 202-byte blocks and
that **block 16 holds the global FX and Master values** at the slot numbers the
parameter records carry in `+12`:

    mirror[block][slot] = 0x800068e4 + 34 + 202*block + 2*slot

Four independent readings agree on that arithmetic. **None of them proves the
DSP acts on it.** Everything so far is the ColdFire's side of the wire; if some
other path also publishes the FX settings and wins, a write into block 16 would
be overwritten and nothing would move. This build converts the reading into a
measurement, and it asks nothing else: no `DEST` change, no capability-mask
edit, no enumeration, no UI, no LFO4.

## What it does

A cave hooked immediately **after** `jsr 0x400db22c` at `0x40027196` -- the
point in the audio-frame ISR where block 16 has been regenerated by the
smoother (`0x400db12a`, called at `0x4002717e`) and the six MIDI performance
modulators have been applied, and before the LFOs run and the frame is built
and sent. The payload keeps a counter in RAM above BSS and writes a triangle
over the **full parameter range**, `0x0000`..`0x7f00`, into

    slot 35, Delay Feedback Gain  ->  B + 34 + 202*16 + 2*35  =  0x800075ec

## Why that slot, and why a triangle this fast

**Because the firmware writes it itself, for an audible reason.** At
`0x40027468`-`0x40027474`, inside the same ISR and gated on `0x4058e550`, stock
code ramps slot 47 down by 127/128 a frame and zeroes slots 42, 35 and 39 --
Reverb Mix, Reverb Decay, **Delay Feedback** and Delay Mix. That is a fade-out
that kills the FX tails, and it is a fifth independent confirmation of the
block-16 arithmetic, arrived at from the write side rather than the read side.
So the slot this build sweeps is one the instrument already treats as live.

**The rate is taken from the site, not guessed.** The hook is in the vector-191
handler `FUN_40025e36`, installed at `0x40025576`; the SSI0-paced eDMA major
loop is 64 minors of 32 bytes over a 64-byte TDM frame, so the ISR runs once
per 32 audio frames -- 1,500 Hz at 48 kHz. Three constants in the image agree:
the DSP send is held off for `0x402876f8` = **1500** ISRs (a one-second
start-up wait), the per-ISR time delta at `0x402a0dec` is **14,400**, and the
LFO phase accumulator wraps at `0x40137530` = **21,600,000** = 14,400 x 1,500.

A full up-and-down sweep therefore takes 2,048 ISR calls = **1.37 s**, which is
one and a half sweeps per bar at 120 BPM. `docs/fx-master-modulation.md` and
`build_lfo4_tick7.py` both record why that matters: `tick7`'s first demo took
about fourteen bars to hear and was nearly reported as broken. A demo whose
effect cannot be told apart from a failure has not measured anything.

## Reading the result

| what is heard | what it means |
|---|---|
| the delay feedback surges and collapses, ~1.4 s a cycle | block 16 is the live FX mirror; §4's remainder is route A, plumbing |
| nothing moves | something else publishes the FX settings and wins; find it before costing anything |
| it moves and then snaps back | block 16 is right, a later writer in the same frame overwrites; move the cave down towards `0x400275a6` |

The Delay page on screen will **not** move in any of these: the UI reads the
control side, not the mirror. Only the sound can answer.

**Safety.** One 6-byte hook whose displaced stock is two straight-line
instructions (`dnfw cave probe`), one cave in the region with the only
hardware-confirmed cave success (`0x4028ea02`, `docs/code-caves.md`), and four
bytes of RAM above BSS. Nothing is written to the +Drive; reflashing stock 1.11
reverts it (`docs/flashing.md`).

No firmware bytes live in this repository: everything is read from the user's
own local image at build time. Output is a .syx under `00_Resources/02_Builds/`
(gitignored), and the patched section alone under `out/fxblock16/` for the
emulator gates.
"""

from __future__ import annotations

import hashlib
import pathlib
import struct
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

from dnfw.cli.files import read_image
from dnfw.container.section import compress
from dnfw.firmware import build as fwbuild
from dnfw.firmware.load import load
from dnfw.image.coldfire import LoadedImage
from dnfw.patch.assemble import assemble, available
from dnfw.patch.cave import Cave, CaveHook, apply

MAIN_OS = 3
BASE = 0x40000400

# The mirror, as docs/fx-master-modulation.md §4c derives it. Every number here
# is re-checked against the image below rather than trusted from the document.
MIRROR_BASE = 0x800068E4          # `lea 0x800068e4,%a2` at 0x400db14a
HEADER = 34                       # bytes before block 0
BLOCK = 202                       # bytes per block
FX_BLOCK = 16                     # the seventeenth block: FX and Master
SLOT = 35                         # Delay Feedback Gain, record 116, `+12` = 35

FULL_SCALE = 0x7F00               # a `0x7f00` range parameter at maximum
STEP_FRAMES = 8                   # ISR calls per step of the ramp
STEPS = 256                       # 128 up, 128 down
ISR_HZ = 1500                     # derived below, and asserted from the image

# Four bytes of RAM above BSS (`docs/memory-map.md`: BSS ends 0x466b74d0, the
# stack descends from 0x48000000). Inside the same 64 KB page as 0x46700000,
# which `lfo4-tick6a` has already used on hardware, and clear of that mod's
# 12 KB and of `bootscreen-bang`'s block at 0x46710000.
COUNTER = 0x46704000

ANCHORS = {
    3_192_192: {                                  # DN2 1.11, MAIN OS
        # The hook: immediately after `jsr 0x400db22c`, the six-source apply.
        "hook": 0x4002719C,
        "stock": "508f42aeff58",                  # addql #8,%sp ; clrl %fp@(-168)
        "cave": (0x4028EA02, 170),                # the cave that ran on hardware
        # Controls, all asserted before anything is written.
        "controls": (
            (0x40027196, "4eb9400db22c", "jsr 0x400db22c -- the six-source apply"),
            (0x4002717E, "4eb9400db12a", "jsr 0x400db12a -- the mirror smoother"),
            (0x400DB14A, "45f9800068e4", "lea 0x800068e4,%a2 -- the mirror base"),
            (0x40027470, "35410d08", "movew %d1,%a2@(3336) -- stock zeroes THIS slot"),
            (0x4002746C, "35410d16", "movew %d1,%a2@(3350) -- and Reverb Decay"),
            (0x400275BA, "486a0d02", "pea %a2@(3330) -- the frame builder reads block 16"),
        ),
        # The rate, read out of the image rather than assumed.
        "rate": (
            (0x402876F8, 1500, "ISRs the DSP send is held off at boot"),
            (0x402A0DEC, 14400, "time units added per ISR"),
        ),
    },
}

STOCK = pathlib.Path("00_Resources/00_Firmware/Digitone_II_OS1.11_dist.zip")
OUT = pathlib.Path("00_Resources/02_Builds/fxblock16_DN2_1.11.syx")
SECTION_OUT = pathlib.Path("out/fxblock16/section_3_MAIN_OS.bin")


def target_address() -> int:
    return MIRROR_BASE + HEADER + BLOCK * FX_BLOCK + 2 * SLOT


def payload_source(target: int) -> str:
    """A full-range triangle on one mirror slot, from a counter in RAM.

    `%d0` and `%d1` are saved and restored although both look dead at the hook,
    because "looks dead" is not a reason to be wrong inside an audio ISR. The
    saves are balanced and complete before the displaced stock runs, so the
    stack the replayed `addql #8,%sp` sees is the stack it expects.
    """
    return f"""    lea     %sp@(-8),%sp
    movem.l %d0-%d1,%sp@
    move.l  {COUNTER:#010x},%d0        | a free-running per-ISR counter
    addq.l  #1,%d0
    move.l  %d0,{COUNTER:#010x}
    lsr.l   #3,%d0                     | one step every {STEP_FRAMES} ISR calls
    move.l  %d0,%d1
    and.l   #0x7f,%d0                  | the ramp
    and.l   #0x80,%d1                  | which half of the triangle
    beq.s   1f
    eor.l   #0x7f,%d0                  | mirror it on the way down
1:  lsl.l   #8,%d0                     | 0x0000..0x7f00, the record's full range
    move.w  %d0,{target:#010x}         | mirror[16][{SLOT}] -- Delay Feedback Gain
    movem.l %sp@,%d0-%d1
    lea     %sp@(8),%sp"""


def main() -> int:
    if not available():
        raise SystemExit(
            "no m68k assembler found -- patch/assemble.py needs m68k-linux-gnu-as "
            "(WSL). See docs/code-caves.md."
        )
    if OUT.exists():
        raise SystemExit(
            f"{OUT} already exists. A build is never rebuilt under a name the owner "
            f"may already have flashed -- give this one a new name instead."
        )

    firmware = load(read_image(STOCK))
    section = firmware.container.find(MAIN_OS)
    content = section.unpack()

    anchor = ANCHORS.get(len(content))
    if anchor is None:
        raise SystemExit(
            f"MAIN OS is {len(content):,} bytes -- no hook anchored for this build "
            f"(docs/version-anchors.md)."
        )

    _check_controls(content, anchor["controls"])
    _check_rate(content, anchor["rate"])

    target = target_address()
    print(f"  target: mirror[{FX_BLOCK}][{SLOT}] = {MIRROR_BASE:#010x} + {HEADER} + "
          f"{BLOCK}*{FX_BLOCK} + 2*{SLOT} = {target:#010x}")
    if target != 0x800075EC:
        raise SystemExit(f"target arithmetic gives {target:#010x}, expected 0x800075ec")

    period = STEP_FRAMES * STEPS
    print(f"  sweep:  0x0000..{FULL_SCALE:#06x} and back in {period} ISR calls "
          f"= {period / ISR_HZ:.2f} s at {ISR_HZ} Hz\n")

    source = payload_source(target)
    print(source + "\n")
    payload = assemble(source)

    hook = CaveHook(id="fxblock16", site=anchor["hook"],
                    stock=bytes.fromhex(anchor["stock"]),
                    payload=payload, cave=Cave(*anchor["cave"]))
    edited = apply(LoadedImage(dest=section.dest, content=content), hook)
    _verify(content, edited, hook)

    SECTION_OUT.parent.mkdir(parents=True, exist_ok=True)
    SECTION_OUT.write_bytes(edited)
    print(f"  wrote {SECTION_OUT}  ({len(edited):,} bytes)")

    syx = fwbuild.build(firmware, {MAIN_OS: compress(section.id, section.dest, edited)})
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(syx)
    print(f"  wrote {OUT}  ({len(syx):,} bytes)")
    print(f"  content sha256 {hashlib.sha256(syx).hexdigest()[:16]}")

    print("\nOn the device: INIT a pattern, turn the track's DEL send up, hold a note.")
    print("  the delay feedback surges and collapses about every 1.4 s")
    print("                         -> the DSP acts on block 16")
    print("  nothing moves          -> something else publishes the FX settings and wins")
    print("  it moves, then snaps back -> a later writer in the same frame overwrites")
    print("  (the Delay page on screen does not move in any case -- the UI reads the")
    print("   control side, not the mirror.)")
    return 0


def _check_controls(content: bytes, controls) -> None:
    """Assert every address this build reasons from, before writing anything.

    `docs/PRINCIPLES.md` §19: a result is only as good as the instrument that
    produced it, and an address taken on trust from a document is not an
    instrument. Each of these is one `dnfw disasm` away by hand.
    """
    for address, expected, why in controls:
        want = bytes.fromhex(expected)
        off = address - BASE
        found = content[off:off + len(want)]
        if found != want:
            raise SystemExit(
                f"{address:#010x}: expected {want.hex(' ')} ({why}) but found "
                f"{found.hex(' ')} -- wrong build or wrong address"
            )
        print(f"  control {address:#010x}  {want.hex(' '):<14}  {why}")


def _check_rate(content: bytes, rate) -> None:
    """The ISR's call rate, counted from the image's own constants."""
    values = {}
    for address, expected, why in rate:
        found = struct.unpack_from(">I", content, address - BASE)[0]
        if found != expected:
            raise SystemExit(
                f"{address:#010x}: expected {expected} ({why}) but found {found}"
            )
        values[address] = found
        print(f"  rate    {address:#010x}  {found:<14}  {why}")
    holdoff, delta = values[0x402876F8], values[0x402A0DEC]
    if holdoff * delta != 21_600_000:
        raise SystemExit(
            f"{holdoff} x {delta} = {holdoff * delta}, not the LFO phase wrap "
            f"21,600,000 at 0x40137530 -- the rate derivation does not close"
        )
    if holdoff != ISR_HZ:
        raise SystemExit(f"the hold-off is {holdoff} ISRs, not {ISR_HZ}")
    print(f"  rate    {holdoff} x {delta} = 21,600,000 = the LFO phase wrap; "
          f"the ISR runs at {ISR_HZ} Hz\n")


def _verify(before: bytes, after: bytes, hook: CaveHook) -> None:
    if len(before) != len(after):
        raise SystemExit("length changed -- a cave patch must not resize the section")
    diffs = [i for i in range(len(before)) if before[i] != after[i]]
    hook_lo, hook_hi = hook.site - BASE, hook.site - BASE + len(hook.stock)
    cave_lo = hook.cave.address - BASE
    cave_hi = cave_lo + hook.cave.capacity
    stray = [i for i in diffs if not (hook_lo <= i < hook_hi or cave_lo <= i < cave_hi)]
    if stray:
        raise SystemExit(f"{len(stray)} bytes changed outside the hook and cave")
    in_hook = sum(1 for i in diffs if hook_lo <= i < hook_hi)
    print(f"  verified: {len(diffs)} bytes changed -- {in_hook} at the hook, "
          f"{len(diffs) - in_hook} in the cave, 0 elsewhere")
    op, destination = struct.unpack_from(">HI", after, hook_lo)
    if op != 0x4EF9 or destination != hook.cave.address:
        raise SystemExit(f"hook is not `jmp {hook.cave.address:#010x}`")
    print(f"  hook reads jmp {hook.cave.address:#010x}")


if __name__ == "__main__":
    raise SystemExit(main())
