"""Copy the 3x5 font into the site, which cannot read a JSON file next to Python.

    python scripts/gen_font3x5.py

Writes `site/js/font3x5.js` from `src/dnfw/font3x5.json`.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

font = json.loads((ROOT / "src/dnfw/font3x5.json").read_text())
(ROOT / "site/js/font3x5.js").write_text(
    "// Generated by scripts/gen_font3x5.py from src/dnfw/font3x5.json -- do not edit by hand.\n"
    f"export const FONT = {json.dumps(font['glyphs'], indent=1)};\n", encoding="utf-8")
print(f"{len(font['glyphs'])} glyphs")
