"""Pre-assemble the lfolength mod (LFO ONE/HALF from the start phase) for the browser and the CLI.

    python scripts/gen_lfolength_code.py

Runs `build_lfo_length.compose` on the user's own stock 1.11 image and writes
what it changed as data, the same pattern as `gen_reloadconfirm_code.py`:

- `edits`: every in-image run the build changes, with the **stock bytes it
  expects** (a guard: the mod refuses any image that differs) and the new bytes.
  The four hooks and the four NOP'd stores: the code is not in the image;
- `guards`: whole instructions around each hook and the code the hooks rely
  on (`build_lfo_length.CONTEXT`), read but not written;
- `code`: the routines, assembled to run at `build_lfo_length.CODE_VA`, as a
  platform `CODE` chunk (`va`, `blob`), and `labels`, where each hook's code
  starts in it (also at the top level).

It refuses to write unless replaying the data on stock gives `compose`'s
output byte for byte. Nothing is derived from Elektron's tables.

Outputs `src/dnfw/mods/lfolength_code.json` and `site/js/mods/lfolength-code.js`.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from dnfw.cli.files import read_image
from dnfw.firmware.load import load

import build_lfo_length as lm

OUT_JSON = ROOT / "src/dnfw/mods/lfolength_code.json"
OUT_JS = ROOT / "site/js/mods/lfolength-code.js"


def main() -> int:
    stock = load(read_image(lm.STOCK)).container.find(lm.MAIN_OS).unpack()
    built = lm.compose(stock, log=lambda *_: None)
    content = built["content"]
    blob = built["blob"]

    n = len(stock)
    # one edit per hook, from the hook list (a byte-diff would split a hook whose new bytes
    # happen to match stock somewhere, as 4ef9.. over 43f9.. does)
    edits = [{"va": va, "stock": stock_bytes.hex(),
              "new": content[va - lm.BASE:va - lm.BASE + len(stock_bytes)].hex(), "what": f"lfolength hook ({label})"}
             for va, stock_bytes, label in lm.HOOKS]
    for va, stock_bytes, new, what in lm.HOLD:          # only the changed bytes; the context is a guard
        diff = [i for i in range(len(new)) if new[i] != stock_bytes[i]]
        lo, hi = diff[0], diff[-1] + 1
        edits.append({"va": va + lo, "stock": stock_bytes[lo:hi].hex(), "new": new[lo:hi].hex(), "what": what})
    changed = [i for i in range(n) if stock[i] != content[i]]
    inside = all(any(e["va"] - lm.BASE <= i < e["va"] - lm.BASE + len(e["stock"]) // 2 for e in edits) for i in changed)
    if not inside:
        raise SystemExit("compose changed bytes outside the hooks; nothing written")

    replay = bytearray(stock)
    for e in edits:
        new = bytes.fromhex(e["new"])
        replay[e["va"] - lm.BASE:e["va"] - lm.BASE + len(new)] = new
    if bytes(replay) != content:
        raise SystemExit("the edits do not reproduce compose's output; nothing written")

    labels = built["labels"]
    code = {
        "os": "Digitone II 1.11",
        "stock_length": n,
        "edits": edits,
        "guards": ([{"va": va, "bytes": want.hex()} for va, want, _ in lm.CONTEXT]
                   + [{"va": va, "bytes": want.hex()} for va, want, _ in lm.HOOKS]
                   + [{"va": va, "bytes": want.hex()} for va, want, _new, _ in lm.HOLD]),
        "labels": labels,
        "code": {"va": lm.CODE_VA, "blob": blob.hex(), "labels": labels},
    }
    OUT_JSON.write_text(json.dumps(code, indent=1) + "\n", newline="\n")
    OUT_JS.write_text("// Generated by scripts/gen_lfolength_code.py -- do not edit by hand.\n"
                      "export const CODE = " + json.dumps(code, indent=1) + ";\n", newline="\n")
    print(f"{len(edits)} edits (hooks and stores), a {len(blob)} B CODE chunk at {lm.CODE_VA:#010x}; "
          + ", ".join(f"{k} {v:#010x}" for k, v in labels.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
