"""Pre-assemble the MIDI arpeggiator mod for the browser and the CLI.

    python scripts/gen_midiarp_code.py

Runs `build_arp_midi_play.compose` on the user's own stock 1.11 image and writes
what it changed as data, the same pattern as `gen_lfo_waves_code.py`:

- `edits`: every in-image run the build changes, with the **stock bytes it
  expects** (a guard: the mod refuses any image that differs) and the new bytes:
  the five hooks and the two menu bytes;
- `code`: since 2026-10-03 the mod's routines are a **platform `CODE` chunk**
  loaded at `CODE_VA` (`dnfw.mods.platform`), not a cave of the image: the cave it
  used (usbprobe's too) stays stock, so it combines with usbprobe;
- `lut_va`: where the N.LEN lookup sits inside the chunk. Its 128 bytes are blanked
  in the data and rebuilt at apply time from the image's own length tables
  (`trig_lengths_va`, `arp_lengths_va`), so nothing derived from Elektron's
  tables ships.

Outputs `src/dnfw/mods/midiarp_code.json` and `site/js/mods/midiarp-code.js`.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from dnfw.cli.files import read_image
from dnfw.firmware.load import load

import build_arp_midi_play as arp

OUT_JSON = ROOT / "src/dnfw/mods/midiarp_code.json"
OUT_JS = ROOT / "site/js/mods/midiarp-code.js"
CODE_VA = 0x467D0000            # free: past arpplocks' code (0x467c8000 + 1,944 B), below 0x467e0000


def main() -> int:
    stock = load(read_image(ROOT / arp.STOCK)).container.find(arp.MAIN_OS).unpack()
    built = arp.compose(stock, log=lambda *_: None, code_base=CODE_VA)
    content = built["content"]
    code_va, _ = built["cave"]
    lut_va, lut_len = built["lut"]
    edits, i, n = [], 0, len(stock)
    while i < n:
        if stock[i] == content[i]:
            i += 1
            continue
        j = i
        while j < n and stock[j] != content[j]:
            j += 1
        edits.append({"va": arp.BASE + i, "stock": stock[i:j].hex(),
                      "new": content[i:j].hex(), "what": "arp edit"})
        i = j

    blob = bytearray(built["blob"])
    blob[lut_va - code_va:lut_va - code_va + lut_len] = bytes(lut_len)

    code = {
        "os": "Digitone II 1.11",
        "stock_length": n,
        "edits": edits,
        # Read, not written: whole instructions around each edit and the code
        # the hooks rely on. An edit's own stock bytes can be a single byte.
        "guards": ([{"va": va, "bytes": want.hex()} for va, want, _ in arp.CONTEXT]
                   + [{"va": va, "bytes": want.hex()} for va, want, _, _ in arp.HOOKS]
                   + [{"va": va, "bytes": want.hex()} for va, want, _, _ in arp.EDITS]),
        "lut_va": lut_va,
        "trig_lengths_va": arp.TRIG_LENGTHS,
        "arp_lengths_va": arp.ARP_LENGTHS,
        "code": {"va": CODE_VA, "blob": bytes(blob).hex()},
    }
    OUT_JSON.write_text(json.dumps(code, indent=1) + "\n", newline="\n")
    OUT_JS.write_text("// Generated by scripts/gen_midiarp_code.py -- do not edit by hand.\n"
                      "export const CODE = " + json.dumps(code, indent=1) + ";\n", newline="\n")
    print(f"{len(edits)} edits, a {len(blob)} B CODE chunk at {CODE_VA:#010x}, lut at {lut_va:#010x}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
