"""Pre-assemble the layering-to-MIDI mod for the browser and the CLI.

    python scripts/gen_layermidi_code.py

Runs `build_layer_midi.compose` on the user's own stock 1.11 image and writes
what it changed as data, the same pattern as `gen_midiarp_code.py`:

- `edits`: every in-image run the build changes, with the **stock bytes it
  expects** (a guard: the mod refuses any image that differs) and the new bytes.
  Only the two hooks: the code is not in the image;
- `guards`: whole instructions around each hook and the code the hooks rely
  on (`build_layer_midi.CONTEXT`), read but not written;
- `code`: the routines, assembled to run at `build_layer_midi.CODE_VA`, as a
  platform `CODE` chunk (`va`, `blob`), and `labels`, where each hook's code
  starts in it (also at the top level).

It refuses to write unless replaying the data on stock gives `compose`'s
output byte for byte. Nothing is derived from Elektron's tables.

Outputs `src/dnfw/mods/layermidi_code.json` and `site/js/mods/layermidi-code.js`.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from dnfw.cli.files import read_image
from dnfw.firmware.load import load

import build_layer_midi as lm

OUT_JSON = ROOT / "src/dnfw/mods/layermidi_code.json"
OUT_JS = ROOT / "site/js/mods/layermidi-code.js"


def main() -> int:
    stock = load(read_image(lm.STOCK)).container.find(lm.MAIN_OS).unpack()
    built = lm.compose(stock, log=lambda *_: None, code_base=lm.CODE_VA)
    content = built["content"]
    blob = built["blob"]

    edits, i, n = [], 0, len(stock)
    while i < n:
        if stock[i] == content[i]:
            i += 1
            continue
        j = i
        while j < n and stock[j] != content[j]:
            j += 1
        edits.append({"va": lm.BASE + i, "stock": stock[i:j].hex(),
                      "new": content[i:j].hex(), "what": "layer-midi hook"})
        i = j
    if len(edits) != len(lm.HOOKS):
        raise SystemExit(f"{len(edits)} edits, expected the {len(lm.HOOKS)} hooks only; nothing written")

    replay = bytearray(stock)
    for e in edits:
        new = bytes.fromhex(e["new"])
        replay[e["va"] - lm.BASE:e["va"] - lm.BASE + len(new)] = new
    if bytes(replay) != content:
        raise SystemExit("the edits do not reproduce compose's output; nothing written")

    _, labels = lm.assemble_stubs(lm.SOURCE, lm.CODE_VA)
    code = {
        "os": "Digitone II 1.11",
        "stock_length": n,
        "edits": edits,
        "guards": ([{"va": va, "bytes": want.hex()} for va, want, _ in lm.CONTEXT]
                   + [{"va": va, "bytes": want.hex()} for va, want, _, _ in lm.HOOKS]),
        "labels": labels,
        "code": {"va": lm.CODE_VA, "blob": blob.hex(), "labels": labels},
    }
    OUT_JSON.write_text(json.dumps(code, indent=1) + "\n", newline="\n")
    OUT_JS.write_text("// Generated by scripts/gen_layermidi_code.py -- do not edit by hand.\n"
                      "export const CODE = " + json.dumps(code, indent=1) + ";\n", newline="\n")
    print(f"{len(edits)} hooks, a {len(blob)} B CODE chunk at {lm.CODE_VA:#010x}; "
          + ", ".join(f"{k} {v:#010x}" for k, v in labels.items()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
