"""Assemble the platform loader once, for Python and the browser.

    python scripts/gen_platform_code.py

Builds `csrc/runtime/loader.S` (`dnfw.patch.loader.build`, an m68k toolchain;
WSL is fine) and writes the bytes the platform installs, so neither the CLI nor
the site needs a toolchain to apply a mod:

    src/dnfw/mods/platform_code.json
    site/js/mods/platform-code.js

It then checks the result against `lfo4_code.json`: LFO4 was the first mod on
this loader and passed on the instrument, so the platform must install exactly
the loader and the start-up call LFO4 installs.
"""

from __future__ import annotations

import json
import pathlib
import struct
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from dnfw.patch import area, loader        # noqa: E402

OUT_JSON = ROOT / "src/dnfw/mods/platform_code.json"
OUT_JS = ROOT / "site/js/mods/platform-code.js"
STOCK_LENGTH = area.AREA_VA - loader.BASE
DATA_LIMIT = 0x46740000                    # lfowaves' NOIS state starts here


def generate() -> dict:
    linked = loader.build()
    hook = b"\x4e\xb9" + struct.pack(">I", linked["dnfw_boot"]) + b"\x4e\x71"
    return {
        "os": "Digitone II 1.11",
        "stock_length": STOCK_LENGTH,
        "calls_va": loader.CALLS_VA, "calls_stock": loader.CALLS_STOCK.hex(), "hook": hook.hex(),
        "cave_va": loader.CAVE_VA, "cave_cap": loader.CAVE_CAP,
        "link_va": loader.LINK_VA, "loader": linked.image.hex(),
        "area_va": area.AREA_VA, "runtime_va": area.RUNTIME_VA, "data_limit": DATA_LIMIT,
    }


def check_against_lfo4(spec: dict) -> None:
    lfo4 = json.loads((ROOT / "src/dnfw/mods/lfo4_code.json").read_text())
    image = bytearray(STOCK_LENGTH)        # blank, but for the stock bytes the edits keep
    calls = spec["calls_va"] - loader.BASE
    image[calls:calls + 8] = loader.CALLS_STOCK
    for e in lfo4["edits"]:
        at = e["va"] - loader.BASE
        new = bytes.fromhex(e["new"])
        image[at:at + len(new)] = new
    link = spec["link_va"] - loader.BASE
    loader_bytes = bytes.fromhex(spec["loader"])
    if image[calls:calls + 8].hex() != spec["hook"]:
        raise SystemExit("the start-up call differs from the one lfo4 installs")
    if bytes(image[link:link + len(loader_bytes)]) != loader_bytes:
        raise SystemExit("the loader differs from the one lfo4 installs")


def main() -> int:
    spec = generate()
    check_against_lfo4(spec)
    OUT_JSON.write_text(json.dumps(spec, indent=1) + "\n", newline="\n")
    OUT_JS.write_text("// Generated by scripts/gen_platform_code.py -- do not edit by hand.\n"
                      f"export const CODE = {json.dumps(spec, indent=1)};\n", newline="\n")
    print(f"loader {len(spec['loader']) // 2} B at 0x{spec['link_va']:08x}; "
          f"hook {spec['hook']}; matches lfo4's")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
