"""Pre-assemble the LFO waves mod for the browser and the CLI.

    python scripts/gen_lfo_waves_code.py

Runs `build_lfo_waves.compose` on the user's own stock 1.11 image and writes what
it changed as data -- the same pattern as `gen_bootscreen_code.py`:

- `edits`: every in-image run the build changes, with the **stock bytes it
  expects** (a guard: the mod refuses any image that differs) and the new bytes;
- `blob`: the appended data, **with every range copied from the stock image
  blanked** -- the first seven entries of each relocated table (`fills`) are read
  from the user's own file at apply time, so no stock table contents ship;
- `tables`: where each of the three wavetables sits in the blob, so a user's own
  table replaces exactly those 224 bytes. The code reads the tables at run time,
  so no reassembly is needed and the glyph follows automatically.

Outputs `src/dnfw/mods/lfowaves_code.json` and `site/js/mods/lfowaves-code.js`.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from dnfw.cli.files import read_image
from dnfw.firmware.load import load

import build_lfo_waves as waves
import wavetables as wt

OUT_JSON = ROOT / "src/dnfw/mods/lfowaves_code.json"
OUT_JS = ROOT / "site/js/mods/lfowaves-code.js"


def main() -> int:
    stock = load(read_image(ROOT / waves.shapes.STOCK)).container.find(waves.MAIN_OS).unpack()
    built = waves.compose(stock, log=lambda *_: None)
    content = built["content"]

    edits, i, n = [], 0, len(stock)
    while i < n:
        if stock[i] == content[i]:
            i += 1
            continue
        j = i
        while j < n and stock[j] != content[j]:
            j += 1
        edits.append({"va": waves.BASE + i, "stock": stock[i:j].hex(), "new": content[i:j].hex()})
        i = j

    blob = bytearray(content[n:])
    fills = []
    for va, source_va, count in built["fills"]:
        off = va - waves.RUNTIME_VA
        blob[off:off + 4 * count] = bytes(4 * count)
        fills.append({"offset": off, "from_va": source_va, "count": count})

    code = {
        "os": "Digitone II 1.11",
        "stock_length": n,
        "area_va": waves.AREA_VA,
        "runtime_va": waves.RUNTIME_VA,
        "magic": waves.MAGIC.decode(),
        "edits": edits,
        "blob": bytes(blob).hex(),
        "fills": fills,
        "tables": [{"name": long, "offset": va - waves.RUNTIME_VA,
                    "frames": wt.FRAMES, "samples": wt.SAMPLES}
                   for (long, _, _), va in zip(wt.TABLES, built["tables"])],
        "waves": [w[1].decode() for w in waves.WAVES],
        "labels": [w[3] for w in waves.WAVES],
    }
    OUT_JSON.write_text(json.dumps(code, indent=1) + "\n")
    OUT_JS.write_text("// Generated by scripts/gen_lfo_waves_code.py -- do not edit by hand.\n"
                      "export const CODE = " + json.dumps(code, indent=1) + ";\n")
    print(f"{len(edits)} edits ({sum(len(e['stock']) // 2 for e in edits)} B), "
          f"blob {len(blob)} B, {len(fills)} fills, tables at "
          + ", ".join(str(t["offset"]) for t in code["tables"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
