"""int16 frames -> what the build compiles: the table's C header and its checksum.

**The table is plain `const` data in our own C image**, linked into the `CODE`
chunk the project's loader copies to `0x46800000` at boot (`dnfw.patch.area`,
`csrc/waverider/table.c`). So "bake" is only this: emit the integers as a C
initialiser, and the probe points beside them, into a header the build
generates. The header is not checked in -- it is output, like the image -- and
nothing in it is hand-written, so the host's expectations and the firmware's
data come from one generator.

**The checksum is order-sensitive on purpose.** A plain sum would not see two
frames swapped or a table read with the wrong stride, which are exactly the
faults a first `load, address, read` can have. Over the table's 16-bit words in
frame-major order:

    h = 0
    for w in words:  h = (h * 31 + w) mod 2^16

`csrc/waverider/table.c` computes the same thing at run time on the
instrument, a slice per telemetry burst.
"""

from __future__ import annotations

import struct

MULT = 31


def words(table: list[list[int]]) -> list[int]:
    """-> the table as unsigned 16-bit words, frame-major, as they sit in memory."""
    return [v & 0xFFFF for f in table for v in f]


def to_bytes(table: list[list[int]]) -> bytes:
    """-> the table as the firmware holds it: big-endian int16, frame-major."""
    return b"".join(struct.pack(">h", v) for f in table for v in f)


def checksum(table: list[list[int]]) -> int:
    h = 0
    for w in words(table):
        h = (h * MULT + w) & 0xFFFF
    return h


def header(table: list[list[int]], probes: list[tuple[int, int]], slice_words: int) -> str:
    """-> `wr_table_data.h`: the geometry, the table's initialiser, the probe points,
    and how many words of checksum each telemetry burst computes."""
    frames, points = len(table), len(table[0])
    if any(len(f) != points for f in table):
        raise ValueError("every frame must have the same number of points")
    for f, i in probes:
        if not (0 <= f < frames and 0 <= i < points):
            raise ValueError(f"probe ({f}, {i}) is outside {frames} x {points}")
    if slice_words <= 0 or (frames * points) % slice_words:
        raise ValueError(f"a checksum slice of {slice_words} does not divide {frames * points} words")
    lines = [
        "/* GENERATED by dnfw.waverider.bake -- do not edit, do not check in.",
        f" * {frames} frames x {points} points, int16, frame-major;"
        f" checksum {checksum(table):#06x} (h = h*{MULT} + w, mod 2^16). */",
        "#ifndef WR_TABLE_DATA_H",
        "#define WR_TABLE_DATA_H",
        "",
        f"#define WR_FRAMES     {frames}",
        f"#define WR_POINTS     {points}",
        f"#define WR_WORDS      {frames * points}",
        f"#define WR_MULT       {MULT}",
        f"#define WR_PROBES     {len(probes)}",
        f"#define WR_SLICE      {slice_words}",
        "",
        "#define WR_PROBE_FRAME_INIT { " + ", ".join(str(f) for f, _ in probes) + " }",
        "#define WR_PROBE_INDEX_INIT { " + ", ".join(str(i) for _, i in probes) + " }",
        "",
        "#define WR_TABLE_INIT { \\",
    ]
    for k, f in enumerate(table):
        lines.append(f"    /* frame {k} */ \\")
        for at in range(0, points, 16):
            lines.append("    " + ", ".join(str(v) for v in f[at:at + 16]) + ", \\")
    lines += ["}", "", "#endif /* WR_TABLE_DATA_H */", ""]
    return "\n".join(lines)

