"""Page 3's noise glyph: a short trace of the noise generator, as page.c's noise_field
draws it, in the same 32-bit integer steps (Q16), so a frame can be predicted pixel for pixel.

The trace is the DSP's generator (live.NoiseVoice): xorshift32, TYPE's filter (Kellet's
economy pink, the brown integrator, DIG's top bit), COLR's tilt and NOIS's gain, one sample
per column after a warm-up, from a fixed seed so it stands still. Its texture is the
sound's; its height is the level. DEC is the outline: each column is NOISE_GLYPH_SECONDS /
width later, so the envelope shrinks the trace at DEC's own time constant (live.noise_tau)."""

import math

from dnfw.waverider import live

Q = 1 << 16
SEED = live.noise_seeds()[0]
WARMUP = 256                       # samples before the first column: the filters settle
NOISE_GLYPH_SECONDS = 1.0          # the strip's width, for the envelope
PINK = tuple((round(a * Q), round(d * Q)) for a, d in live.NOISE_PINK)
PINK_DIRECT = round(live.NOISE_PINK_DIRECT * Q)
BROWN = tuple(round(v * Q) for v in live.NOISE_BROWN)
DIG = round(live.NOISE_DIG * Q)


def _s32(v: int) -> int:
    v &= 0xFFFFFFFF
    return v - (1 << 32) if v >> 31 else v


def qmul(v: int, c: int) -> int:
    """v (Q16, signed) x c (Q16, 0 <= c < 2^17), as page.c's qmul: whole and fraction parts,
    no 64-bit product."""
    if c >= Q:
        return _s32(v + qmul(v, c - Q))
    hi, lo = v >> 16, v & 0xFFFF
    return _s32(hi * c + ((lo * c) >> 16))


def env_steps(width: int) -> tuple[int, ...]:
    """DEC 0..126 -> the envelope's factor per column (Q16), for a strip of `width` columns."""
    dt = NOISE_GLYPH_SECONDS / width
    return tuple(min(Q - 1, round(Q * math.exp(-dt / live.noise_tau(v)))) for v in range(live.NOISE_INF))


def samples(nois: int, typ: int, colr: int, dec: int, width: int) -> list[int]:
    """The trace, Q16, for NOIS 0..127, TYPE 0..3, COLR 0..127 (64 flat), DEC 0..127 (Inf)."""
    x, pink, brown, lp = SEED, [0, 0, 0], 0, 0
    env, k = Q - 1, (env_steps(width)[dec] if dec < live.NOISE_INF else None)
    typ = min(typ, 3)
    out = []
    for i in range(WARMUP + width):
        x = live.xorshift32(x)
        w = _s32(x) >> 15
        if typ == 0:
            n = w
        elif typ == 1:
            for j, (a, d) in enumerate(PINK):
                pink[j] = _s32(qmul(pink[j], a) + qmul(w, d))
            n = (pink[0] + pink[1] + pink[2] + qmul(w, PINK_DIRECT)) >> 2
        elif typ == 2:
            brown = _s32(qmul(brown, BROWN[0]) + qmul(w, BROWN[1]))
            n = brown
        else:
            n = -DIG if x >> 31 else DIG
        lp += (n - lp) >> 3
        y = n - (((colr - 64) * lp) >> 6)
        if i >= WARMUP:
            y = y * nois // 100 if y >= 0 else -((-y) * nois // 100)
            if k is not None:
                y = qmul(y, env)
                env = qmul(env, k)
            out.append(y)
    return out


def rows(trace: list[int], half: int, unit: int) -> list[int]:
    """Each sample's offset from the strip's centre line, in pixels: one unit (full scale)
    is `unit` pixels, clipped to +-half."""
    return [max(-half, min(half, (y * unit + (Q >> 1)) >> 16)) for y in trace]


def header(width: int) -> str:
    """csrc/ui/noise_env.h: env_steps as ui/noise_strip.c's table."""
    vals = env_steps(width)
    body = ",\n".join("    " + ", ".join(f"{v:5d}" for v in vals[i:i + 10]) for i in range(0, len(vals), 10))
    return ("/* generated by scripts/gen_noise_env.py from dnfw.waverider.noise_glyph.env_steps:\n"
            f" * DEC 0..126 -> the envelope's factor per column (Q16), {width} columns = "
            f"{NOISE_GLYPH_SECONDS:g} s */\n"
            f"#define NOISE_ENV_WIDTH {width}\n"
            "static const unsigned short noise_env[127] = {\n" + body + "\n};\n")


# The sub over the noise (owner, 2026-10-07): the sub's own wave at its own scale, WAVE's
# shape (live.sub_value), SUB's height, and OCT as cycles across the strip (-1 oct two,
# -2 oct one until OCT -3 came; now -1 four, -2 two, -3 one, so each shape shows whole).
# SUB_GLYPH 3 draws it solid over the noise dotted on odd columns; 4 draws one
# line, their sum, as the two are added into the track.

def sub_value(phase: int, wave: int) -> int:
    """live.sub_value in Q16, as page.c's sub_q16."""
    top = phase >> 31
    h = (((phase << 1) & 0xFFFFFFFF) >> 16) >> 1          # x mod 0.5, Q16 (0..32767)
    if wave == 0:
        y = (h * (32768 - h)) >> 12
        return -y if top else y
    if wave == 1:
        return 4 * (h if top else 32768 - h) - Q
    if wave == 2:
        return -Q if top else Q
    return Q if phase < 0x40000000 else -21845


def sub_samples(sub: int, octave: int, wave: int, width: int) -> list[int]:
    """The sub's trace, Q16, for SUB 0..127, OCT 0 (-1) / 1 (-2) / 2 (-3), WAVE 0..3."""
    step = ((0xFFFFFFFF // width) * 4) >> min(octave, 2)
    out = []
    for i in range(width):
        y = sub_value((i * step) & 0xFFFFFFFF, min(wave, 3))
        out.append(y * sub // 100 if y >= 0 else -((-y) * sub // 100))
    return out


def _line(r: list[int], x0: int, cy: int, every: int = 1) -> set:
    lit = set()
    for i, v in enumerate(r):
        if (i % every) == 0:
            a, b = (v, v) if i == 0 else (min(r[i - 1], v), max(r[i - 1], v))
            lit |= {(x0 + i, cy + y) for y in range(a, b + 1)}
    return lit


# page.c's SUB_LAYOUT 4 (the default): the strip x 24..121 by y 15..39, full scale 10 px;
# layouts 1 and 3 drew it 4 px to full scale in a shorter strip
LAYOUT4 = dict(x0=24, x1=121, y0=15, y1=39, unit=10)


def strip(noise: tuple, sub: tuple, x0: int, x1: int, y0: int, y1: int, glyph: int = 3,
          unit: int = 4) -> set:
    """The strip's lit pixels (x, y up), as page.c's noise_field draws them.
    noise = (NOIS, TYPE, COLR, DEC), sub = (SUB, OCT, WAVE); unit is NOISE_UNIT."""
    w, cy, half = x1 - x0 + 1, (y0 + y1) >> 1, (y1 - y0) >> 1
    nz = samples(*noise, w)
    sb = sub_samples(*sub, w)
    if glyph == 4:
        return _line(rows([a + b for a, b in zip(nz, sb)], half, unit), x0, cy)
    lit = _line(rows(nz, half, unit), x0, cy, 2 if sub[0] else 1)
    if sub[0]:
        lit |= _line(rows(sb, half, unit), x0, cy)
    return lit
